### PR TITLE
Added simple functionality to open up direct channel and to send a me…

### PR DESCRIPTION
**Pull request by twcurrie**
Added simple functionality to open up direct channel and to send a message via direct channel.

### CODE REVIEW

**Comment by twcurrie** [comment]
I don't have a lot of experience with the Python testing framework, so I leave that to the experts for now.

**Comment by tonytan4ever** [comment]
👍  Allow slackbot to make DM would be very useful, especially when conversing in user specific/confidential messages. I had a case where I need to automate a task where a user account name and password need to be passed to bot, and this is where DM can come into play.

**Comment by DannyHinshaw** [comment]
Curious on the status of this PR, this would be a really nice feature to have. Do we just need unit tests? If that's all it's waiting on for merge I can give it a go.

**Comment by lins05** [comment]
Thanks, the change LGTM, I'll add the tests later.

**Pull request merged**
