### PR TITLE
General python3 support

### PR DESCRIPTION
**Pull request by josegonzalez**
- Better py3 support removing imp when possible
- Default message personalization
- Possibility of creating a custom docs reply
- PluginManagerinto it's own file as is used by dispatcher too

### CODE REVIEW

**Comment by josegonzalez** [comment]
Refs #51

**Comment by lins05** [comment]
LGTM! I'll merge it after the travis ci build finishes.

**Comment by josegonzalez** [comment]
@merqurio <3

@lins05 can we see a point release?

**Comment by lins05** [comment]
@josegonzalez the only new feature since 0.3.0 release is the support of reacting to messages with emojis with `message.react()`. So I don't think it's worth a new release right now. 

https://github.com/lins05/slackbot/compare/0.3.0...6fb0791

**Comment by josegonzalez** [comment]
You can change the default message now as well. At least a 0.3.1 would be nice :)

**Comment by lins05** [comment]
Makes sense. I'll do that soon.

**Comment by josegonzalez** [comment]
<3

**Comment by ei-grad** [comment]
:-1:

**Comment by josegonzalez** [comment]
@ei-grad is there something here you are specifically against, or a bug this introduced?

**Comment by merqurio** [comment]
#55

**Pull request merged**
