### PR TITLE
Change 'Private Group' terminology to 'Private Channel'

### PR DESCRIPTION
**Pull request by DannyHinshaw**
Most all changes were made in the testing architecture, with a few changes in the CONTRIBUTING as well (for `slackbot_test_settings.py` setup)

Included backwards compatibility patch for TravisCI where environment variables may still be using the outdated 'SLACKBOT_TEST_GROUP'.

### CODE REVIEW

**Comment by DannyHinshaw** [comment]
Forgot to note that all tests pass for me both locally and with Travis (including with env var 'GROUP').

**Comment by DannyHinshaw** [comment]
Closed for committing un-squashed branch. Working on a new PR

**Comment by jtatum** [comment]
In the future, don't sweat it :) I tend to squash on merge anyhow. Also, you can use git rebase -i to squash commits on your branch, then do a push --force (while you never want to force push an active branch, it's just fine on a feature/topic branch).

**Comment by DannyHinshaw** [comment]
Cool, appreciate it. I actually thought I had done the rebase successfully until I looked at my PR, noticed it didn't take (probably didn't --force). Rebasing is still new to me so it was at least good practice haha. Thanks

**Pull request closed without merging**
