### PR TITLE
Look in config/ for settings

### PR DESCRIPTION
**Pull request by xaocon**
Look in config/ for settings if settings can't be found in the original
locations and config exists.

I think it's nice to have a separate place for config files if you want.

### CODE REVIEW

**Comment by xaocon** [comment]
Hi. Don't want to seem pushy (no pun intended) but is this something you'll be interested in? I've noticed some commits going in but this is pretty straightforward and hasn't seen any action in the 3 months it's been open. Let me know if there's anything I can do to help

**Comment by lucywang000** [comment]
@xaocon Thx for the patch, but I don't think this is generally useful. Any specific reason for using a "config" package?

**Comment by xaocon** [comment]
Up to you. I think it's nice if you're building a large bot and want some organization to your files instead of having everything sitting in a single folder.

I'm about to push up a change that is more organized but does the same thing. If you don't want it feel free to just close and I'll just maintain my fork. Just thought it might be nice to have the option.

**Comment by lucywang000** [comment]
@xaocon Thx for the comment, sorry but I still feel it's too specific so not fit to put it in the library itself.

**Pull request closed without merging**
