### PR TITLE
Add @listen_to decorator, answers by multiple plugins, message formatting

### PR DESCRIPTION
**Pull request by gpailler**
- Added @listen_to decorator. With this new decorator, the bot listens all messages on channels where he's invited and can send responses
- Use webapi to send message (and keep rtm send message) to be able to format message (rtm API doesn't allow to format messages)
- Add support for bot icon (required when using webapi send message)
- Allow several plugins to respond (and not only the first matching plugin)

### CODE REVIEW

**Comment by lins05** [comment]
Thanks for your patch! However, since this PR involves rather big change, could you please send pull request to the develop branch instead of master?

Also, could you please add test cases for the changes?

**Comment by gpailler** [comment]
Oh, I didn't noticed the develop branch.
Sure, I will prepare a new PR on develop with green tests

**Comment by lins05** [comment]
The testing requires a slack organization and one user and one bot. Please see https://github.com/lins05/slackbot/tree/e80a269e6e7133944600b4b3da2ba90b6facda48/tests/functional/settings.py#L12-L18. 

I created a slack organization for testing purpose, if you need the details please tell me.

**Comment by gpailler** [comment]
I saw that. I planned to create a new organisation but if you can send me the details it's more simple. I already configured Travis and I just need environments variables.

**Comment by lins05** [comment]
On second thought I think we'd better not use the same organization for testing right now, since the current tests code assumes that there is only one concurrent tests running on travis ci, and make asserts based on that, e.g. [here](https://github.com/lins05/slackbot/tree/e80a269e6e7133944600b4b3da2ba90b6facda48/tests/functional/driver.py#L138).

So please go ahead and configure a new slack organization for testing, sorry for the confusion. I would improve the testing part (code & doc) so that it would be simpler for others to run the tests and contribute.

**Comment by gpailler** [comment]
Ok, I will create a new test organization.

**Pull request closed without merging**
