### PR TITLE
add ability to post reactions to messages

### PR DESCRIPTION
**Pull request by neveryan**
```
@listen_to('.*')
def eggplant(message):
    message.react('eggplant')
```

### CODE REVIEW

**Comment by lins05** [comment]
LGTM, it could be very useful. 

Do you mind adding a functional test case for it? For example, we can add a plugin function in `slackbot/plugins/hello.py` which responds to certain messages by adding a `thumbup` reaction and assert there is a [reaction_added](https://api.slack.com/events/reaction_added) event happened in this channel. 

Take [wait_for_file_uploaded](https://github.com/lins05/slackbot/blob/97f4f0adfab092ba61e08d42860c2f58617945d9/tests/functional/driver.py#L112-L118) in the test driver class as an example of how to assert some events happened.

**Comment by merqurio** [comment]
This is really cool!

**Comment by neveryan** [comment]
I hit two snags in adding that test:
1- The api docs of the reaction event aren't accurate. So it checks both for the field name in practice and by the docs. I dropped the Slack folks a note about this.
2- You can an emoji's alias name in the event (e.g. +1 / thumbsup). I chose one with no default alias to work around this.

**Comment by neveryan** [comment]
s/can an/can get an/

**Comment by lins05** [comment]
@jdryan thanks for the patch! I'll update the readme soon.

**Pull request merged**
