### PR TITLE
Send tracebacks to a specified channel/group/user

### LINKED ISSUE #46: Send stacktraces to a specific user or group
Occasionally I will rush out new commands for my bot or users will try combinations that potentially get picked up by the regex but actually break the function and this causes exceptions to be thrown in the chat room.

I think this should be changed so that whenever an exception is thrown the stacktrace is sent to the maintainer(s), and I suppose you could inform the user that "There was an error" or not even.

### PR DESCRIPTION
**Pull request by jtatum**
Adds new config option: ERRORS_TO, and a client helper function for finding
channels/groups.
Fixes #46

### CODE REVIEW

**Comment by lins05** [comment]
The change LGTM, but please do not mix the new feature with code reformatting of other modules. (I know the project should impose a consistent code style, which I'm working on.)

Would you mind removing the unnecessary changes? I'll be happy to merge it after that.

**Comment by jtatum** [comment]
Merged develop, removed unnecessary changes, fixed dispatcher unit tests

**Comment by lins05** [comment]
@jtatum Sorry for the delay, do you mind rebase it again? Thanks!

**Comment by jtatum** [comment]
Done, and tests look good https://travis-ci.org/jtatum/slackbot/builds/123217636

**Comment by lins05** [comment]
Thanks!

**Pull request merged**
