### PR TITLE
Closes #52  and suggested modifications added

### LINKED ISSUE #52: PROPOSAL: Slackbot settings when bot is instanced
We wanted to create more than a bot, different instances. Right now all the settings of the bot are defined in the `slackbot_settings.py`files, but I think that a more intuitive implementation would be to pass thos configurations as attributes of the class instantiation.

``` python
bot = Bot(api_token="<your-api-token>",
          plugins_dir="your_plugins_directory/"
          default_reply=<my_func or str>)
```

### PR DESCRIPTION
**Pull request by merqurio**
README.md:
- Update to reflect modifications in default_reply function
- Suggestions by @lins05

slackbot/bot.py:
- Remove logging settings

slackbot/dispatcher.py:
- Restructure _default_reply()

### CODE REVIEW

**Comment by merqurio** [comment]
Sorry I opened a new PR But I was unable to squash both commits and maintain the same PR :disappointed:

**Comment by lins05** [comment]
The code lgtm, can you also add tests for this new feature?

**Comment by lins05** [comment]
Also the commit message is toooo long, can you replace it with one or two short sentences?

**Comment by jtatum** [comment]
Is slackbot/settings.py still needed? This will probably break tests, especially on travis - see tests/functional/slackbot_settings.py. Does run.py still work after this change? Do tests pass?

**Comment by merqurio** [comment]
I'm working on the tests, sorry I forgot to tell you that @jtatum

**Pull request closed without merging**
